### ISSUE TITLE
Change in 0.0.7 breaks downstream usage

### ISSUE THREAD

**Issue by jarrodconnolly** [galvez/unihead#2]
A special case in the Proxy wrapper around `HeadManager` appears to have been removed between 0.0.6 and 0.0.7 which is used by the core renderers in `fastify-vite` .

```
        if (elem === 'update') {
          return initialHead => head.update(initialHead)
        }
```

More specifics here:
https://github.com/fastify/fastify-vite/issues/168

**Comment by galvez** [comment]
Published `v0.0.8`.
